"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 17:52:47.382646
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('journey_state', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('semester_start', sa.Date(), nullable=True),
    sa.Column('semester_end', sa.Date(), nullable=True),
    sa.Column('missed_after_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('courses',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('syllabus', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_courses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('trigger_log',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trigger_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trigger_log')),
    sa.UniqueConstraint('user_id', 'key', name='uq_trigger_log_user_key')
    )
    with op.batch_alter_table('trigger_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trigger_log_user_id'), ['user_id'], unique=False)

    op.create_table('assignments',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assignments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('class_slots',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_class_slots_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_class_slots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_slots'))
    )
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_slots_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_slots_user_id'), ['user_id'], unique=False)

    op.create_table('course_memory',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('topics_per_week', sa.Float(), nullable=False),
    sa.Column('syllabus_position', sa.Text(), nullable=False),
    sa.Column('pace_note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_memory_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_memory_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_memory')),
    sa.UniqueConstraint('course_id', name=op.f('uq_course_memory_course_id'))
    )
    with op.batch_alter_table('course_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_memory_user_id'), ['user_id'], unique=False)

    op.create_table('exams',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('scope_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_exams_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_jobs_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_topics_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_user_id'), ['user_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_agent_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('class_sessions',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=False),
    sa.Column('topic_ids', sa.JSON(), nullable=False),
    sa.Column('missed_reason', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_class_sessions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['class_slots.id'], name=op.f('fk_class_sessions_slot_id_class_slots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_class_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_sessions')),
    sa.UniqueConstraint('slot_id', 'session_date', name='uq_class_sessions_slot_date')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('exam_packs',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('notes_cutoff', sa.DateTime(), nullable=True),
    sa.Column('built_at', sa.DateTime(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_exam_packs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_packs_exam_id_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_packs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_packs'))
    )
    with op.batch_alter_table('exam_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_packs_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_packs_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_packs_user_id'), ['user_id'], unique=False)

    op.create_table('note_sections',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_note_sections_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_note_sections_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_note_sections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_sections'))
    )
    with op.batch_alter_table('note_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_sections_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_sections_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_sections_user_id'), ['user_id'], unique=False)

    op.create_table('topic_dependencies',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_topic_dependencies_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['topics.id'], name=op.f('fk_topic_dependencies_depends_on_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_dependencies_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_dependencies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_dependencies')),
    sa.UniqueConstraint('topic_id', 'depends_on_id', name='uq_topic_dependencies_pair')
    )
    with op.batch_alter_table('topic_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_dependencies_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_dependencies_user_id'), ['user_id'], unique=False)

    op.create_table('agent_steps',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_steps_run_id_agent_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_steps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps'))
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_user_id'), ['user_id'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_chunks_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['note_sections.id'], name=op.f('fk_chunks_section_id_note_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_chunks_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chunks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_user_id'), ['user_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('priced', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_llm_calls_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_calls_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_task'), ['task'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_user_id'), ['user_id'], unique=False)

    op.create_table('mock_exams',
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['exam_packs.id'], name=op.f('fk_mock_exams_pack_id_exam_packs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mock_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_exams'))
    )
    with op.batch_alter_table('mock_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_exams_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_exams_user_id'), ['user_id'], unique=False)

    op.create_table('study_guide_sections',
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('cited_section_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['exam_packs.id'], name=op.f('fk_study_guide_sections_pack_id_exam_packs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_study_guide_sections_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_guide_sections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_guide_sections'))
    )
    with op.batch_alter_table('study_guide_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_guide_sections_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_guide_sections_user_id'), ['user_id'], unique=False)

    op.create_table('uploads',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('class_session_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('detected_type', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('status_message', sa.String(length=300), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('extracted_md', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], name=op.f('fk_uploads_class_session_id_class_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_uploads_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_uploads_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_user_id'), ['user_id'], unique=False)

    op.create_table('exam_attempts',
    sa.Column('mock_exam_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('self_scores', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], name=op.f('fk_exam_attempts_mock_exam_id_mock_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempts'))
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempts_mock_exam_id'), ['mock_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('mock_exam_id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('solution_md', sa.Text(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('cited_section_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['mock_exam_id'], ['mock_exams.id'], name=op.f('fk_exam_questions_mock_exam_id_mock_exams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['exam_packs.id'], name=op.f('fk_exam_questions_pack_id_exam_packs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_exam_questions_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_questions'))
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_mock_exam_id'), ['mock_exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_pack_id'), ['pack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_user_id'), ['user_id'], unique=False)

    op.create_table('ingestion_log',
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('path_taken', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('legibility_score', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_ingestion_log_upload_id_uploads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ingestion_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_log'))
    )
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_log_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_user_id'), ['user_id'], unique=False)

    op.create_table('open_questions',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('source_upload_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_open_questions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_upload_id'], ['uploads.id'], name=op.f('fk_open_questions_source_upload_id_uploads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_open_questions_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_open_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_questions'))
    )
    with op.batch_alter_table('open_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_questions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_questions_user_id'), ['user_id'], unique=False)

    op.create_table('section_sources',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['note_sections.id'], name=op.f('fk_section_sources_section_id_note_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_section_sources_upload_id_uploads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_section_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_sources')),
    sa.UniqueConstraint('section_id', 'upload_id', name='uq_section_sources_pair')
    )
    with op.batch_alter_table('section_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_sources_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_sources_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_sources_user_id'), ['user_id'], unique=False)

    # sqlite-vec store for note chunks (384-d = default embedding model). user_id is a partition key,
    # so every KNN query is constrained to one user inside the vector index itself.
    op.execute("CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks_384 USING vec0("
               "chunk_id INTEGER PRIMARY KEY, user_id TEXT PARTITION KEY, embedding FLOAT[384] distance_metric=cosine)")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS vec_chunks_384")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_section_sources_upload_id'))
        batch_op.drop_index(batch_op.f('ix_section_sources_section_id'))

    op.drop_table('section_sources')
    with op.batch_alter_table('open_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_open_questions_course_id'))

    op.drop_table('open_questions')
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_upload_id'))

    op.drop_table('ingestion_log')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_pack_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_mock_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_mock_exam_id'))

    op.drop_table('exam_attempts')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_course_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('study_guide_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_guide_sections_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_guide_sections_pack_id'))

    op.drop_table('study_guide_sections')
    with op.batch_alter_table('mock_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_exams_user_id'))
        batch_op.drop_index(batch_op.f('ix_mock_exams_pack_id'))

    op.drop_table('mock_exams')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_task'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_user_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_topic_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_section_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_course_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('topic_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_dependencies_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_dependencies_course_id'))

    op.drop_table('topic_dependencies')
    with op.batch_alter_table('note_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_sections_user_id'))
        batch_op.drop_index(batch_op.f('ix_note_sections_topic_id'))
        batch_op.drop_index(batch_op.f('ix_note_sections_course_id'))

    op.drop_table('note_sections')
    with op.batch_alter_table('exam_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_packs_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_packs_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_packs_course_id'))

    op.drop_table('exam_packs')
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_course_id'))

    op.drop_table('class_sessions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_topics_course_id'))

    op.drop_table('topics')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_after'))

    op.drop_table('jobs')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_user_id'))
        batch_op.drop_index(batch_op.f('ix_exams_course_id'))

    op.drop_table('exams')
    with op.batch_alter_table('course_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_memory_user_id'))

    op.drop_table('course_memory')
    with op.batch_alter_table('class_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_slots_user_id'))
        batch_op.drop_index(batch_op.f('ix_class_slots_course_id'))

    op.drop_table('class_slots')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_course_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('trigger_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trigger_log_user_id'))

    op.drop_table('trigger_log')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_type'))

    op.drop_table('events')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))

    op.drop_table('courses')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
