# pg_hba.conf - Configuración Segura

# "local" es para conexiones Unix domain socket.
local   all             all                                     scram-sha-256

# Conexiones locales (IPv4 / IPv6)
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# --- REGLAS DE LA APLICACIÓN ---

# Permitir al usuario de la APLICACIÓN conectarse a la BBDD de la APLICACIÓN
# (Usamos el nombre literal 'REDACTED' que definimos en el .env)
host    tutor_ia_db     REDACTED        0.0.0.0/0               scram-sha-256

# Permitir al usuario de REPLICACIÓN conectarse a la BBDD de REPLICACIÓN
# (Usamos el nombre literal 'replicator' que definimos en el .env)
host    replication     replicator      0.0.0.0/0               scram-sha-256

# --- RECHAZAR EL RESTO ---
# (La línea 'host all all 0.0.0.0/0 md5' ha sido eliminada por seguridad)